### ISSUE TITLE
バージョン指定した場合に、インストールがおわらない

### ISSUE THREAD

**Issue by mtmtkzm** [liginc/lig-interactive-generator#25]
```
➜  develop lig -v
0.3.2
➜  develop lig
? Choose Environment Type wordpress
? Type Project( You can use only a-z0-9 and "-") wp-rider2
? Type WordPress version (Empty will be "latest") latest
? Type PHP version (Empty will be "7.3") 7.3
? Type MySQL version (Empty will be "5.7") 5.7
```

でインストール

で、こうなる

```
⠋ [preparing](node:19298) UnhandledPromiseRejectionWarning: ReferenceError: WP_VER is not defined
    at /Users/matsumoto_kazuma/.nodebrew/node/v10.15.3/lib/node_modules/lig-interactive-generator/script/wordpress.js:56:126
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:19298) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19298) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠹ [preparing]
```

**Comment by mtmtkzm** [comment]
WP_VER is not defined
たぶんこの子やなあ

**Comment by mtmtkzm** [comment]
```
➜  develop lig -v
0.3.2
➜  develop lig
? Choose Environment Type wordpress
? Type Project( You can use only a-z0-9 and "-") wp-rider
? Type WordPress version (Empty will be "latest")
? Type PHP version (Empty will be "7.3")
? Type MySQL version (Empty will be "5.7")
⠋ [download] https://github.com/liginc/lig-docker-wordpress.gitCloning into 'wp-rider/tmp'...
✔ [download] https://github.com/liginc/lig-docker-wordpress.git
⠋ [download] https://github.com/liginc/laravel-mix-boilerplate-wordpress.gitCloning into 'wp-rider/tmp'...
✔ [download] https://github.com/liginc/laravel-mix-boilerplate-wordpress.git
⠋ [download] https://github.com/liginc/lig-wordpress-template.gitCloning into 'wp-rider/tmp'...
✔ [download] https://github.com/liginc/lig-wordpress-template.git
✔ [preparing]
➜  develop
```

ちなみにエンター連打すると成功するっぽい

**Comment by ghost** [comment]
https://github.com/liginc/lig-interactive-generator/pull/27
解決
